---
services:
  mysqldb:
    build: database/
    image: bloodimages:dbimage
    ports:
     - "3306:3306"
       
  appcont:
     build: .
     image: bloodimages:appimage
     ports: 
       - "1111:80"
